// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UIRegularExpressionForWindow UIRegularExpressionForWindow
        {
            get
            {
                if ((this.mUIRegularExpressionForWindow == null))
                {
                    this.mUIRegularExpressionForWindow = new UIRegularExpressionForWindow();
                }
                return this.mUIRegularExpressionForWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIRegularExpressionForWindow mUIRegularExpressionForWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRegularExpressionForWindow : WinWindow
    {
        
        public UIRegularExpressionForWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Regular Expression - Form";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Regular Expression - Form");
            #endregion
        }
        
        #region Properties
        public UITxtExpNumberWindow UITxtExpNumberWindow
        {
            get
            {
                if ((this.mUITxtExpNumberWindow == null))
                {
                    this.mUITxtExpNumberWindow = new UITxtExpNumberWindow(this);
                }
                return this.mUITxtExpNumberWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtExpNumberWindow mUITxtExpNumberWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UITxtExpNumberWindow : WinWindow
    {
        
        public UITxtExpNumberWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "TxtExpNumber";
            this.WindowTitles.Add("Regular Expression - Form");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtExpNumberEdit
        {
            get
            {
                if ((this.mUITxtExpNumberEdit == null))
                {
                    this.mUITxtExpNumberEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtExpNumberEdit.WindowTitles.Add("Regular Expression - Form");
                    #endregion
                }
                return this.mUITxtExpNumberEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtExpNumberEdit;
        #endregion
    }
}
